# ./configs/wazuh/manager/filebeat.yml
# Intern Filebeat for wazuh-manager

#filebeat.inputs: []  # usamos module, no inputs sueltos

filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false

setup.template.json.enabled: true
setup.template.overwrite: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ['https://172.20.0.20:9200']
  username: 'admin'
  password: 'admin'
  ssl:
    certificate_authorities: ['/etc/filebeat/certs/root-ca.pem']
    verification_mode: full

logging.metrics.enabled: false

seccomp:
  default_action: allow
  syscalls:
  - action: allow
    names:
      - rseq



# Con esto se cambio filebeat interno para que no envie directo a elacticsearch sino
# a Logstach para evitar duplicados con filebeat externo y el tag _type deprecado
# ojo esto configuración lo único que logró fue dar problemas

#filebeat.modules:
#  - module: wazuh
#    alerts:
#      enabled: false # desactivated to evade duplicates, we are using an external filebeat
#    archives:
#      enabled: false

#setup.template.enabled: true
#setup.template.overwrite: true
#setup.ilm.enabled: false

#  Cambia a Logstash (NO Elasticsearch directo)
#output.logstash:
#  hosts: ["logstash:5044"]

#logging.metrics.enabled: false

#seccomp:
#  default_action: allow
#  syscalls:
#    - action: allow
#      names: [rseq]
