# ./configs/wazuh/manager/filebeat.yml
# Internal Filebeat for wazuh-manager

#filebeat.inputs: []  # using module, not standalone inputs

filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false

setup.template.json.enabled: true
setup.template.overwrite: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ['https://172.20.0.20:9200']
  username: 'admin'
  password: 'admin'
  ssl:
    certificate_authorities: ['/etc/filebeat/certs/root-ca.pem']
    verification_mode: full

logging.metrics.enabled: false

seccomp:
  default_action: allow
  syscalls:
  - action: allow
    names:
      - rseq



# Attempted change: Internal Filebeat configured to send data to Logstash
# instead of Elasticsearch, to avoid duplicates with external Filebeat
# and to bypass deprecated _type field. 
# Note: This configuration caused issues and was reverted.

#filebeat.modules:
#  - module: wazuh
#    alerts:
#      enabled: false  # disabled to prevent duplicates, external Filebeat in use
#    archives:
#      enabled: false
#
#setup.template.enabled: true
#setup.template.overwrite: true
#setup.ilm.enabled: false
#
#  Switch output to Logstash (NOT direct Elasticsearch)
#output.logstash:
#  hosts: ["logstash:5044"]
#
#logging.metrics.enabled: false
#
#seccomp:
#  default_action: allow
#  syscalls:
#    - action: allow
#      names: [rseq]
