# configs/elk/filebeat/filebeat.yml
# === Filebeat sidecar to read Wazuh alerts.json ===
strict.perms: false

filebeat.inputs:
  - type: filestream
    id: wazuh-alerts
    enabled: true
    paths: ["/var/ossec/logs/alerts/alerts.json"]

    # Each line is JSON (NDJSON)
    parsers:
      - ndjson:
          overwrite_keys: true
          add_error_key: true

    # Allow startup even if file is small (<1024 bytes)
    prospector.scanner.fingerprint.length: 64
    prospector.scanner.fingerprint.offset: 0

    # Disabled due to issues
    processors:
    #  - rename:
    #      fields:
    #        - from: "timestamp"
    #         to: "@timestamp"
    #      ignore_missing: true

# Output to Logstash (beats input on port 5044)
output.logstash:
  hosts: ["logstash:5044"]
