input {
  http {
    port => 8080
    codec => json
  }
}

filter {
  mutate {
    add_field => { "processed_by" => "logstash" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "elastic"
    password => "changeme123!"
    index => "test-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
